on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: setup deps
      run: sudo apt update; sudo apt install axel binfmt-support qemu-user-static -y
    - name: clone fs
      run: axel https://build.nethunter.com/kalifs/kalifs-latest/kalifs-arm64-full.tar.xz
    - name: extract fs
      run: mkdir -pv fs; sudo tar -xvpf kalifs-arm64-full.tar.xz -C fs
    - name: Setup qemu
      run: sudo cp /bin/qemu-aarch64-static fs/kali-arm64/bin ;sudo service binfmt-support start
    - name: mount fs
      run: sudo mount --rbind /dev fs/kali-arm64/dev; sudo mount -t proc proc fs/kali-arm64/proc;sudo mount -t sysfs /sys fs/kali-arm64/sys
    - name: setup network
      run: sudo touch fs/etc/resolv.conf;echo nameserver 8.8.8.8 | sudo tee fs/etc/resolv.conf
    - name: fix up fs
      run: sudo cp -v payload/stage1.sh fs/kali-arm64/stage1.sh; sudo cp -v payload/stage2.sh fs/kali-arm64/stage2.sh; sudo chroot fs/kali-arm64 bash /stage1.sh; sudo chroot fs/kali-arm64 bash /stage2.sh
    - name: Trigger upgrade and theme installation
      run: sudo cp -v payload/stage3.sh fs/kali-arm64/stage3.sh;sudo chroot fs/kali-arm64 bash /stage3.sh
    - name: setupvnc
      run: sudo cp -v payload/stage4.sh fs/kali-arm64/stage4.sh;sudo chroot fs/kali-arm64 bash /stage4.sh
    - name: cleanup
      run: sudo chroot fs apt clean
    - name: make tarbal
      run: sudo chroot fs/kali-arm64 tar -cvpJf /kali-arm64-rebuild-latest.tar.gz --exclude-caches-all --exclude=/dev/*  --exclude=/sys/* --exclude=/proc/* --exclude=/run/* --exclude=/tmp/* --exclude=/kali-arm64-rebuild-latest.tar.gz /* --one-file-system || true
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: kali-arm64-rebuild-latest.tar.gz
        path : fs/kali-arm64/kali-arm64-rebuild-latest.tar.gz