name: Test-WOrkflow
on: [push]

jobs:
  compile-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-deps.yml
      - run: sudo apt update; sudo apt install g++ -y
      # give exec permissions to the file
      - run: chmod +x scripts/compile.sh
      - run: ./scripts/compile.sh
      - run: ./hello.so