name: Test-WOrkflow
on: [push]
jobs:
  BuildImpishArm64:
    runs-on: ubuntu-latest
    steps:
      - env:
          PREFIX: "impish-arm64-tarball"
          OVERRIDER_COMPRESSION_TYPE: "gzip"
          ENABLE_EXIT: true
          ENABLE_USER_SETUP: false

      - uses: actions/checkout@v2
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Satify Dependencies
        run: sudo apt update; sudo apt install git build-essential binfmt-support qemu-user-static debootstrap -y
      - name: Trigger fs-cook
        run: bash scripts/build-impish.sh
      - name: Save Builds
        uses: actions/upload-artifact@v2
        with:
          name: impish-image
          path: out/impish-arm64-tarball.tar.gz
          mime-type: application/gzip
      