name: Test-WOrkflow
on: [push]
jobs:
  BuildImpish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Satify Dependencies
        run: sudo apt update; sudo apt install git build-essential binfmt-support qemu-user-static debootstrap -y
      - name: Trigger fs-cook
        run: bash scripts/build-impish.sh
      - name: Save Builds
        uses: actions/upload-artifact@v2
        with:
          name: impish-raw-artifacts
          path: /home/runner/work/test-repo-/test-repo-/fs-cook/out/impish-raw-*.tar.gz
          
      